server:
  port: 8021
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver    url: jdbc:mysql://localhost:3306/untact
    username: root
    password: root
mybatis:
  type-aliases-package: com.sbs.untact.dto